--<ScriptOptions statementTerminator="GO"/>

CREATE SCHEMA "Schema"
GO

CREATE TABLE "Schema"."CLIENT" (
		"ID" CHAR(10) NULL,
		"FIRSTNAME" CHAR(10) NULL,
		"SURNAME" CHAR(10) NULL,
		"CLIENT_ID" INT NOT NULL IDENTITY (1,1),
		"USER_ID" INT NOT NULL,
		"COMPANYCOMPANY_ID" INT NOT NULL
	)
GO

CREATE TABLE "Schema"."COMMENT" (
		"ID" CHAR(10) NULL,
		"TEXT" CHAR(10) NULL,
		"DATE" CHAR(10) NULL,
		"TYPE" CHAR(10) NULL,
		"COMMENT_ID" INT NOT NULL IDENTITY (1,1)
	)
GO

CREATE TABLE "Schema"."COMPANY" (
		"NAME" CHAR(10) NULL,
		"NIP" CHAR(10) NULL,
		"COMPANY_ID" INT NOT NULL IDENTITY (1,1),
		"DEPARTMENTDEPARTMENT_ID" INT NOT NULL
	)
GO

CREATE TABLE "Schema"."DEPARTMENT" (
		"NAME" CHAR(10) NULL,
		"ID" CHAR(10) NULL,
		"ADDRESS" CHAR(10) NULL,
		"CONTACT" CHAR(10) NULL,
		"DEPARTMENT_ID" INT NOT NULL IDENTITY (1,1)
	)
GO

CREATE TABLE "Schema"."EMPLOYEE" (
		"FISRTNAME" CHAR(10) NULL,
		"SURNAME" CHAR(10) NULL,
		"POSITION" CHAR(10) NULL,
		"ADRESS" CHAR(10) NULL,
		"PESEL" CHAR(10) NULL,
		"EMPLOYEE_ID" INT NOT NULL IDENTITY (1,1),
		"USER_ID" INT NOT NULL,
		"TICKETTICKET_ID" INT NOT NULL
	)
GO

CREATE TABLE "Schema"."ROLE" (
		"ID" CHAR(10) NULL,
		"NAME" CHAR(10) NULL,
		"CODE" CHAR(10) NULL,
		"ROLE_ID" INT NOT NULL IDENTITY (1,1)
	)
GO

CREATE TABLE "Schema"."SLA" (
		"REALIZATIONTIME" CHAR(10) NULL,
		"SIGNIFICANCE" CHAR(10) NULL,
		"PRIORITY" CHAR(10) NULL,
		"SLA_ID" INT NOT NULL IDENTITY (1,1),
		"FIRMACOMPANY_ID" INT NOT NULL
	)
GO

CREATE TABLE "Schema"."SYSTEMHISTORY" (
		"ACTION" CHAR(10) NULL,
		"ID" CHAR(10) NULL,
		"SYSTEMHISTORY_ID" INT NOT NULL IDENTITY (1,1)
	)
GO

CREATE TABLE "Schema"."TICKET" (
		"TICKET_ID" INT NOT NULL IDENTITY (1,1),
		"CLIENTUSER_ID" INT NOT NULL,
		"CLIENTCLIENT_ID" INT NOT NULL
	)
GO

CREATE TABLE "Schema"."USER" (
		"USERNAME" CHAR(10) NULL,
		"PASSWORD" CHAR(10) NULL,
		"EMAIL" CHAR(10) NULL,
		"ID" CHAR(10) NULL,
		"USER_ID" INT NOT NULL IDENTITY (1,1)
	)
GO

ALTER TABLE "Schema"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY CLUSTERED
	("USER_ID",
	 "CLIENT_ID")
GO

ALTER TABLE "Schema"."COMMENT" ADD CONSTRAINT "COMMENT_PK" PRIMARY KEY CLUSTERED
	("COMMENT_ID")
GO

ALTER TABLE "Schema"."COMPANY" ADD CONSTRAINT "COMPANY_PK" PRIMARY KEY CLUSTERED
	("COMPANY_ID")
GO

ALTER TABLE "Schema"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY CLUSTERED
	("DEPARTMENT_ID")
GO

ALTER TABLE "Schema"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY CLUSTERED
	("USER_ID",
	 "EMPLOYEE_ID")
GO

ALTER TABLE "Schema"."ROLE" ADD CONSTRAINT "ROLE_PK" PRIMARY KEY CLUSTERED
	("ROLE_ID")
GO

ALTER TABLE "Schema"."SLA" ADD CONSTRAINT "SLA_PK" PRIMARY KEY CLUSTERED
	("SLA_ID")
GO

ALTER TABLE "Schema"."SYSTEMHISTORY" ADD CONSTRAINT "SYSTEMHISTORY_PK" PRIMARY KEY CLUSTERED
	("SYSTEMHISTORY_ID")
GO

ALTER TABLE "Schema"."TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY CLUSTERED
	("TICKET_ID")
GO

ALTER TABLE "Schema"."USER" ADD CONSTRAINT "USER_PK" PRIMARY KEY CLUSTERED
	("USER_ID")
GO

ALTER TABLE "Schema"."CLIENT" ADD CONSTRAINT "CLIENT_COMPANY_FK" FOREIGN KEY
	("COMPANYCOMPANY_ID")
	REFERENCES "Schema"."COMPANY"
	("COMPANY_ID")
GO

ALTER TABLE "Schema"."CLIENT" ADD CONSTRAINT "CLIENT_USER_FK" FOREIGN KEY
	("USER_ID")
	REFERENCES "Schema"."USER"
	("USER_ID")
GO

ALTER TABLE "Schema"."COMPANY" ADD CONSTRAINT "COMPANY_DEPARTMENT_FK" FOREIGN KEY
	("DEPARTMENTDEPARTMENT_ID")
	REFERENCES "Schema"."DEPARTMENT"
	("DEPARTMENT_ID")
GO

ALTER TABLE "Schema"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_TICKET_FK" FOREIGN KEY
	("TICKETTICKET_ID")
	REFERENCES "Schema"."TICKET"
	("TICKET_ID")
GO

ALTER TABLE "Schema"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_USER_FK" FOREIGN KEY
	("USER_ID")
	REFERENCES "Schema"."USER"
	("USER_ID")
GO

ALTER TABLE "Schema"."SLA" ADD CONSTRAINT "SLA_COMPANY_FK" FOREIGN KEY
	("FIRMACOMPANY_ID")
	REFERENCES "Schema"."COMPANY"
	("COMPANY_ID")
GO

ALTER TABLE "Schema"."TICKET" ADD CONSTRAINT "TICKET_CLIENT_FK" FOREIGN KEY
	("CLIENTUSER_ID",
	 "CLIENTCLIENT_ID")
	REFERENCES "Schema"."CLIENT"
	("USER_ID",
	 "CLIENT_ID")
GO

